<#

Load scripts.

Generated by: Walter Eaves

Generated on: 08/01/2015

I've added an initialization object -args. It's not used, but it might be useful.

#>

param()
  
. {
  param(
     [validateset("a","b","c")]
     $letter
  )
  
     function Get-Letter {
        "You initialized the module with $letter"
     }
} @args

$script:Logman="$env:windir\system32\logman.exe"

gci $psscriptroot\*.ps1 | % { . $_.FullName }

$Settings0 = (Get-Settings)

Export-ModuleMember Get-Letter
Export-ModuleMember -Variable Settings0

