<#

Load scripts.

Generated by: Walter Eaves

Generated on: 08/01/2015

I've added an initialization object -args. It's not used, but it might be useful.

#>

param()
  
. {
  param(
     [validateset("a","b","c")]
     $letter
  )
  
     function Get-Letter {
        "You initialized the module with $letter"
     }
} @args

$script:Logman="$env:windir\system32\logman.exe"

# Source all the .ps1 files (and not the invisible ones maintained by the editor.)

gci $psscriptroot\*.ps1 |
  ? { $_.BaseName -notlike '.*' } | 
  ? { $_.Extension -eq '.ps1' } | 
  % { . $_.FullName }

# Initialize a singleton.

$Settings0 = (Get-Settings)

$script:secpasswd = ConvertTo-SecureString '3Ip$7tsA' -AsPlainText -Force
$script:mycreds = New-Object System.Management.Automation.PSCredential ("owner", $secpasswd)

Export-ModuleMember Get-Letter
Export-ModuleMember -Variable Settings0

